on: [push]

jobs:
  action_test:
    runs-on: ubuntu-latest
    name: action test
    steps:
    - uses: actions/checkout@v1
    - name: SBT action test
      id: sbt
      uses: ./
      with:
        commands: '"test" "package"'
        sbt_project_directory: ./test
      env:
        external_resolver_eltoro_nexus: "El Toro Nexus Resolver" at "http://nexus.middleearth.eltoro.com/repository/maven-public/"
