on: [push]

jobs:
  action_test:
    runs-on: ubuntu-latest
    name: action test
    steps:
    - uses: actions/checkout@v1
    - name: SBT action test
      id: sbt
      uses: ./
      with:
        commands: aetherDeploy
        sbt_project_directory: ./test
        settings_sbt: |
          externalResolvers += "GitHub lokkju Apache Maven Packages" at "https://maven.pkg.github.com/lokkju/github-action-sbt"
          publishTo := Some("GitHub lokkju Apache Maven Packages" at "https://maven.pkg.github.com/lokkju/github-action-sbt")
          credentials += Credentials("GitHub lokkju Apache Maven Packages", "maven.pkg.github.com", "lokkju", "${{ secrets.GITHUB_TOKEN }}")
